### ISSUE TITLE
Duplicates behaviour

### ISSUE THREAD

**Issue by olso** [gradecam/angular-fast-repeat#2]
https://github.com/gradecam/angular-fast-repeat/blob/master/src/fastRepeat.js#L5 means that they are tracked by this incrementing id, right?

**Comment by physicsrob** [comment]
That's right.  The object gets modified with a $$fastRepeatId attribute that allows us to track the object.  If your object has an id or _id attribute this is used for the $$fastRepeatId, but it still gets set.  If I remember correctly angular strips out the $$ attributes when serializing.
